### ISSUE TITLE
Cannot use subquery

### ISSUE THREAD

**Issue by willy140198** [cube2222/octosql#157]
Hi, I try to query using subquery like this
SELECT pta2.*, tam1.created_at as ticket_agent_mapping_create FROM premier_ticket_aml pta2
LEFT JOIN (
	SELECT * FROM ticket_agent_mapping tam
		WHERE tam.agent_role = 'aml_agent'
) as tam1 ON pta2.ticket_id = tam1.ticket_id
ORDER BY pta2.id ASC;
But its doesnt work. Did I do something wrong?

**Comment by cube2222** [comment]
What does "it doesn't work" mean?

**Comment by willy140198** [comment]
It's return error
![IMG-20191231-WA0004](https://user-images.githubusercontent.com/37429573/71634996-21406f00-2c53-11ea-89fc-4728a5654f55.jpg)

**Comment by cube2222** [comment]
Ok, I see the bug causing this now.

You probably have a null as some ticket id. And after the migration to protobuf, it seems like pushdown stopped working well with SQL db's cause of type differences. (struct{} vs null)

Thank you for the issue! I'll try fix this ASAP.

The binary of the latest release (not master branch) should probably work well, as that is pre-protobuf.

**Comment by willy140198** [comment]
Thank you!
Which branch is pre-protobuf?

**Comment by cube2222** [comment]
The v0.2.0 release.

**Comment by cube2222** [comment]
Sorry, my bad. You were correctly using the v0.2.0 release. The error is fixed on the master branch. So please try to use that and let me know if you have further issues. There may be regressions because of the rewrite to protobuf, but there shouldn't be (and I don't know of any yet). Feel free to post issues however.

**Comment by willy140198** [comment]
Hi, I had used the master branch and still face this error when using left join.
![image](https://user-images.githubusercontent.com/37429573/73174587-af1c5680-413a-11ea-876e-e2e5ef7ce37b.png)

**Comment by cube2222** [comment]
How did you install octosql from the master branch?
One approach is to git clone and then go into cmd/octosql -> go install
the other is
```
GO111MODULE=on go get -u github.com/cube2222/octosql/cmd/octosql@ec2e084778fbb191fd87afbe32cb53ee78fe87b2
```

**Comment by willy140198** [comment]
I already try it, but no luck. any other suggestion?

**Comment by cube2222** [comment]
Ah sorry, didn't see the new error message on my phone.

OctoSQL doesn't allow you to compare two values of varying types. You should be able to fix this using the coalesce function: https://github.com/cube2222/octosql/wiki/Function-Documentation#coalesce

Changing the field to an int like -1 if it's null.

**Comment by cube2222** [comment]
Small example

JSON data:
```
{
  "number": 2
}
{
  "number": 3
}
{
  "number": null
}
{
  "number": 4
}
```

usage:
```
> octosql 'select coalesce(n.number, 5) as number FROM numbers n'
+--------+
| number |
+--------+
|      2 |
|      3 |
|      5 |
|      4 |
+--------+
```

**Comment by JasiekChomiak** [comment]
Closing for lack of activity
